spring:
  application:
    name: zuul-gateway-service
server:
  port: 9000  
  
zuul:
  routes:
    catalog-service:
      path: /catalog-service/**
      url: http://localhost:8081
    cart:
      path: /cart-service/**
      url: http://localhost:8082/cart-service